version: '3.7'

services:
  my-blog:
    # image: nginx:alpine
    image: ghcr.io/zvonimirsun/nginx:stable-alpine-brotli
    container_name: my-blog-container
    restart: always
    volumes:
      - .:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8010:80"
    networks:
      - proxy
networks:
  proxy:
    external: true
